Fix build failing since https://github.com/TrinityCore/TrinityCore/commit/8e169280683cb3b32c5e98d1f56784d4c4e2e4ca
/TrinityCore/src/server/game/Maps/Map.cpp:2448:22: fatal error: 
      variable 'areaId' is used uninitialized whenever 'if' condition is false
      [-Wsometimes-uninitialized]
        if (GridMap* gmap = const_cast<Map*>(this)->GetGrid(x, y))