Build: fix variable order initialization error
fatal error: field 'Action' will be initialized after field 'Validator' [-Wreorder]

(cherry picked from commit 71e7394b74bc36467f478986c0bd179e18e04fb8)